name: publish
run-name: ${{ github.actor }} is publishing stuff
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Retrieve theme
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.92.2"

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: bpcreech/bpcreech.github.io
          publish_dir: ./public
          #   keep_files: true
          user_name: bpcreech
          user_email: hi@bpcreech.com
          publish_branch: master
        #   cname: example.com
